package tacit.mcp

import tacit.core.*
import Context.*
import tacit.executor.{CodeRecorder, ExecutionResult, ReplSession}

import io.circe.*
import io.circe.syntax.*

/** Build info loaded from version.properties (generated by sbt). */
private object BuildInfo:
  private val props = java.util.Properties()
  locally:
    val stream = classOf[McpServer].getResourceAsStream("/version.properties")
    if stream != null then
      try props.load(stream)
      finally stream.close()
  val version: String = Option(props.getProperty("version")).getOrElse("0.0.0-unknown")
  val name: String = Option(props.getProperty("name")).getOrElse("TACIT")

/** MCP Server implementation for Scala code execution */
class McpServer(using Context):
  private val ProtocolVersion = "2025-11-25"

  private val DefaultSessionId = "default"

  private lazy val defaultSession: ReplSession = new ReplSession(DefaultSessionId)

  private inline def recorder: Option[CodeRecorder] = ctx.recorder

  /** Handle a JSON-RPC request and return a response */
  def handleRequest(request: JsonRpcRequest): Option[JsonRpcResponse] =
    request.method match
      case "initialize" =>
        handleInitialize(request)
      case "notifications/initialized" | "initialized" =>
        // Notification, no response needed (accept both for backward compat)
        None
      case "tools/list" =>
        handleToolsList(request)
      case "tools/call" =>
        handleToolsCall(request)
      case "ping" =>
        Some(JsonRpcResponse.success(request.id, Json.obj()))
      case "notifications/cancelled" =>
        // Notification, no response needed
        None
      case other if other.startsWith("notifications/") =>
        // All notifications - no response needed
        None
      case other =>
        Some(JsonRpcResponse.error(
          request.id,
          JsonRpcError.MethodNotFound,
          s"Method not found: $other"
        ))

  private def handleInitialize(request: JsonRpcRequest): Option[JsonRpcResponse] =
    val result = InitializeResult(
      protocolVersion = ProtocolVersion,
      capabilities = ServerCapabilities(
        tools = Some(ToolsCapability(listChanged = Some(true)))
      ),
      serverInfo = ServerInfo(
        name = s"${BuildInfo.name} MCP",
        version = BuildInfo.version
      )
    )
    Some(JsonRpcResponse.success(request.id, result.asJson))

  private def handleToolsList(request: JsonRpcRequest): Option[JsonRpcResponse] =
    val result = ToolsListResult(Tools.all)
    Some(JsonRpcResponse.success(request.id, result.asJson))

  private def handleToolsCall(request: JsonRpcRequest): Option[JsonRpcResponse] =
    val result = for
      params <- request.params.toRight("Missing params")
      callParams <- params.as[CallToolParams].left.map(_.message)
      toolResult <- callTool(callParams.name, callParams.arguments)
    yield toolResult

    result match
      case Right(toolResult) =>
        Some(JsonRpcResponse.success(request.id, toolResult.asJson))
      case Left(error) =>
        Some(JsonRpcResponse.error(
          request.id,
          JsonRpcError.InvalidParams,
          error
        ))

  private def callTool(name: String, arguments: Option[Json]): Either[String, CallToolResult] =
    name match
      case "eval_scala" => evalScala(arguments)
      case other        => Left(s"Unknown tool: $other")

  private def evalScala(arguments: Option[Json]): Either[String, CallToolResult] =
    for
      args <- arguments.toRight("Missing arguments")
      code <- args.hcursor.get[String]("code").left.map(_.message)
    yield
      val result = defaultSession.execute(code)
      recorder.foreach(_.record(code, DefaultSessionId, result))
      formatExecutionResult(result)

  private def formatExecutionResult(result: ExecutionResult): CallToolResult =
    val output = result.error match
      case Some(err) if result.output.nonEmpty =>
        s"${result.output}\n\nError: $err"
      case Some(err) =>
        s"Error: $err"
      case None =>
        if result.output.isEmpty then "(no output)" else result.output

    CallToolResult(
      content = List(TextContent(output)),
      isError = if result.success then None else Some(true)
    )
